name: update-templates-auto
on:
 schedule:
   - cron: '0 2 */20 * *'

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
      with:
        persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
        fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
    - name: Update ugc template
      run: |
        cd templates
        mv ugc-template old-ugc-template
        bash update-ugc.sh
        rm -rf old-ugc-template
        mv tl-template old-tl-template
        bash update-tl.sh
        rm -rf old-tl-template
        cd ../
        git config --local user.email "dark-matter7232@users.noreply.github.com"
        git config --local user.name "Dark-Matter7232"
        git add -A
        git commit -m "Update Template" -a
    - name: Push packages
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}
